### ISSUE TITLE
`./gradlew build` comes errors

### ISSUE THREAD

**Issue by Egbert1** [FISCO-BCOS/group-signature-client#11]
when i use the `./gradlew build` command, some errors come:
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.ethereum:solcJ-all:0.4.25.
     Required by:
         project : > org.fisco-bcos:web3sdk:2.2.0
      > Could not resolve org.ethereum:solcJ-all:0.4.25.
         > Could not get resource 'https://dl.bintray.com/ethereum/maven/org/ethereum/solcJ-all/0.4.25/solcJ-all-0.4.25.pom'.
            > Could not GET 'https://dl.bintray.com/ethereum/maven/org/ethereum/solcJ-all/0.4.25/solcJ-all-0.4.25.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

**Comment by a5400** [comment]
你好，你在运行java -cp 'conf/:lib/*:apps/*' org.fisco.bcos.groupsig.app.Main deploy_ring_sig 'hello' 'ring1' '0' '4'时有没有出现
please wait ...
extra error message: /github/home/.hunter/_Base/0ba8099/8cf628f/0b4fef9/Build/bcos-boostssl/Source/bcos-boostssl/websocket/WsService.cpp(223): Throw in function void bcos::boostssl::ws::WsService::syncConnectToEndpoints(bcos::boostssl::ws::EndPointsPtr)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: [end of stream:/127.0.0.1:20200, end of stream:/127.0.0.1:20201]
这个问题
